// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3f98093f-6842-4702-a78e-6431ab11bf12";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDiffChange();
void onKpChange();
void onPowerChange();
void onStartChange();

float diff;
float kp;
int power;
bool start;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(diff, READWRITE, ON_CHANGE, onDiffChange);
  ArduinoCloud.addProperty(kp, READWRITE, ON_CHANGE, onKpChange);
  ArduinoCloud.addProperty(power, READWRITE, ON_CHANGE, onPowerChange);
  ArduinoCloud.addProperty(start, READWRITE, ON_CHANGE, onStartChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
